export const COLLAPSE = 'COLLAPSE'
export const LOADING = 'LOADING'
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const REFRESH = 'REFRESH'
export const CURRENT_USER = 'CURRENT_USER'
